# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site wide configuration
theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Xiaorui (Jeremy) Zhu 朱浚铭"
description: "Only the paranoid survive! Here are my research, interests and life."
baseurl:  # the subpath of your site, e.g. "/blog"
url: "https://xiaoruizhu.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "/docs/favicon.png" # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: 200 # 200
mathjax: 
  enable: true # MathJax equations, e.g. true, false (default)
  combo: "tex-svg" # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags: "ams" # "none", "ams" (default), "all"
google_fonts: 
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "UA-54280540-1" # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus: 
  shortname: "jeremyzhu" # Disqus shortname, e.g. "my_disqus_shortname"
twitter: 
  username: "dale_zhu" # site's Twitter username, e.g. "mmistakes"



# Liquid
liquid: 
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed: 
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins: 
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults: 
  # Posts defaults
  - scope: 
      path: "_posts"
      type: posts
    values: 
      layout: post
      share: true

# Site Author
author: 
  name: Xiaorui Zhu
  picture: /docs/images/bio-photo.jpg
  email: zhuxiaorui1989@gmail.com
  twitter: dale_zhu
  links: 
    - title: Twitter
      url: https://twitter.com/dale_zhu
      icon: fab fa-twitter-square
    - title: Facebook
      url: https://facebook.com/xiaor.zhu
      icon: fab fa-facebook
    - title: GitHub
      url: https://github.com/xiaoruizhu
      icon: fab fa-github-square
    - title: Stackexchange
      url: https://stackexchange.com/users/3539424/xiaorui-zhu
      icon: fab fa-stack-exchange
    - title: Linkedin
      url: https://www.linkedin.com/in/jeremychu89/
      icon: fab fa-linkedin

# weibo: 1246701103
# google:
  # plus: 118415573512961148625
  # analytics: UA-54280540-1
