# Site wide configuration
theme: jekyll-theme-so-simple
title: Xiaorui (Jeremy) Zhu 朱浚铭
locale: en_US
description: Only the paranoid survive! Here are my research, interests and life.
logo: site-logo.png
search: true
baseurl: # the subpath of your site, e.g. "/blog"
url: https://xiaoruizhu.github.io
date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: 200 # 200
mathjax: true # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: UA-54280540-1 # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: jeremyzhu # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: dale_zhu # site's Twitter username, e.g. "mmistakes"


# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Search
search_full_content: false # can have performance implications for large sites

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate


# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Xiaorui (Jeremy) Zhu
  picture: bio-photo.jpg
  email: zhuxiaorui1989@gmail.com
  twitter: dale_zhu
  links:
    - title: Ph.D. Candadite at University of Cincinnati
      url: http://homepages.uc.edu/~zhuxr/
      icon: site-logo.png

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/dale_zhu
    icon: fab fa-twitter-square
  - title: Facebook
    url: https://facebook.com/xiaor.zhu
    icon: fab fa-facebook-square
  - title: Linkedin
    url: https://linkedin.com/in/jeremychu89
    icon: fab fa-linkedin
  - title: Github
    url: https://github.com/xiaoruizhu
    icon: fab fa-github-square
  - title: Stackexchange
    url: https://stackexchange.com/users/3539424/xiaorui-zhu
    icon: fab fa-stack-exchange
  - title: Weibo
    url: https://www.weibo.com/u/1246701103
    icon: fab fa-weibo
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
